// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBocMfEXYvmPZaX3NCS_MiYFseCuuXPr6Y',
    appId: '1:667241799422:web:de3a8edf5e47e5c0118faf',
    messagingSenderId: '667241799422',
    projectId: 'rivinha-gym',
    authDomain: 'rivinha-gym.firebaseapp.com',
    storageBucket: 'rivinha-gym.appspot.com',
    measurementId: 'G-BWMHY2YS90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ5aDT13JPlOlra-_lYQASMUjdsCuvHcY',
    appId: '1:667241799422:android:41d39249ee14694f118faf',
    messagingSenderId: '667241799422',
    projectId: 'rivinha-gym',
    storageBucket: 'rivinha-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0OdH3AVc0oafpdoF4zdE9bJkGdHqEy0k',
    appId: '1:667241799422:ios:1e4660467c6b4300118faf',
    messagingSenderId: '667241799422',
    projectId: 'rivinha-gym',
    storageBucket: 'rivinha-gym.appspot.com',
    iosBundleId: 'com.example.rivinhaFitness',
  );
}
